#!/usr/bin/python
# -*- encoding: utf-8 -*-

import argparse
import sys
import os
import re
import fnmatch
import tempfile
from itertools import chain

from colorama import init as colorama_init, Fore, Back, Style

def main():
    # parse the command line
    args = parse_args()

    if args.colour:
        colorama_init()

    root = os.path.abspath(args.root)
    files = (f for f in walk_files(root)
                if fnmatch.fnmatch(f, args.include))

    regexp = re.compile(args.pattern)
    
    if args.delete:
        replace(files, regexp, None, colour=args.colour)
    elif args.sub:
        replace(files, regexp, args.sub, colour=args.colour)
    else:
        search(files, regexp, colour=args.colour)


def search(files, regexp, colour=False):
    matches = []
    for filename in files:
        for f,l,d in search_regexp(filename, regexp, colour=colour):
            if colour:
                print_colour(f,l,d)
            else:
                sys.stdout.write('{}:{}:{}\n'.format(f,l,d.rstrip()))


def replace(files, regexp, sub, colour=False):
    # find files containing regexp
    matches = set()
    for filename in files:
        for f,l,d in search_regexp(filename, regexp):
            matches.add(f)
            break

    # for each file containing regexp, apply changes
    if not sub:
        sub = ''

    for filename in matches:
        print filename
        with tempfile.TemporaryFile() as tmp:
            with open(filename, 'r') as infile:
                tmp.write(re.sub(regexp, sub, infile.read()))

            tmp.seek(0)

            with open(filename, 'w') as infile:
                infile.write(tmp.read())


def print_colour(f, l, d):
    sys.stdout.write(Style.BRIGHT + Fore.MAGENTA)
    sys.stdout.write(f)

    sys.stdout.write(Style.RESET_ALL + Fore.CYAN)
    sys.stdout.write(':')

    sys.stdout.write(Style.BRIGHT + Fore.BLUE)
    sys.stdout.write('{}'.format(l))

    sys.stdout.write(Style.RESET_ALL + Fore.CYAN)
    sys.stdout.write(':')

    sys.stdout.write(Style.RESET_ALL + Fore.RESET)
    sys.stdout.write(d.rstrip())

    sys.stdout.write('\n')


def search_regexp(filename, regexp, colour=False):
    found = False

    with open(filename, 'rt') as data:
        for lineno, line in enumerate(data):
            r = regexp.search(line)
            if r is not None:
                if colour:
                    line = (Style.RESET_ALL + line[0:r.start()] +
                        Fore.RED + Style.BRIGHT + line[r.start(): r.end()] +
                        Style.RESET_ALL + line[r.end():])

                found = True
                yield (filename, lineno, line)

    if not found:
        return


def walk_files(path='.'):
    """ returns a list of all files nested under path """
    def isdir_tuple(d):
        return ((os.path.isdir(d) and (d, True)) or (d, False))

    # find all entries, and check whether each is a file or a dir
    entries = [isdir_tuple(os.path.join(path, p)) for p in os.listdir(path)]

    # split entries into two generators
    dirs = (d for d, isdir in entries if isdir)
    files = (f for f, isdir in entries if not isdir)

    # chain the files in this folder with all of the files in any subfolders
    return chain(files, flatten(walk_files(d) for d in dirs))


def flatten(l):
    """ flatten a nested list """
    return (val for sublist in l for val in sublist)


def parse_args():
    """ Command line argument parser """

    parser = argparse.ArgumentParser()
    parser.add_argument('--root', '-r',
            help='path to root of project',
            action='store',
            default='.'
            )
    parser.add_argument('--include', '-i',
            help='shell pattern of files to find (eg "*.py")',
            action='store',
            default='*'
            )
    parser.add_argument('--colour', '-c', 
            help='colourize output',
            action='store_true',
            )
    parser.add_argument('pattern',
            help='regular expression to search for',
            action='store',
            default=r'.'
            )
    parser.add_argument('--sub', '-s',
            help='replacement expression',
            action='store'
            )
    parser.add_argument('--delete', '-d',
            help='delete text',
            action='store_true'
            )
    args = parser.parse_args()
    return args
    

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.stdout.write('\n')
